// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDohDlN10cNk9cSJVtGqrPVZeE_4U0u4sA',
    appId: '1:757865993715:android:4d5f580d8e161a9f08ee86',
    messagingSenderId: '757865993715',
    projectId: 'heartsync-6792f',
    storageBucket: 'heartsync-6792f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2HSNy6IbIod6fzQK71XlQFFlu_7RodzU',
    appId: '1:757865993715:web:f937b10de00861dc08ee86',
    messagingSenderId: '757865993715',
    projectId: 'heartsync-6792f',
    authDomain: 'heartsync-6792f.firebaseapp.com',
    storageBucket: 'heartsync-6792f.firebasestorage.app',
    measurementId: 'G-SX1ZM7LLFG',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2HSNy6IbIod6fzQK71XlQFFlu_7RodzU',
    appId: '1:757865993715:web:f937b10de00861dc08ee86',
    messagingSenderId: '757865993715',
    projectId: 'heartsync-6792f',
    authDomain: 'heartsync-6792f.firebaseapp.com',
    storageBucket: 'heartsync-6792f.firebasestorage.app',
    measurementId: 'G-SX1ZM7LLFG',
  );

}